apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: wether-app
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: 496391058917.dkr.ecr.ap-south-1.amazonaws.com/maxweather-staging/weather-api:$ImageTag
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
